import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="title" content="E-commerce Template"></meta>
        <meta name="description" content="Users can modify the designs what they in website this feature is available in our e-commerce website."></meta>
        <meta name="keywords" content="E-commerce, purchase, women dresses, men dresses"></meta>
        <meta name="robots" content="index, follow"></meta>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <meta name="language" content="English"></meta>
    
        {/* open graph */}
        <meta property="og:type" content="Dynamic website" />
        <meta property="og:title" content="E-commerce Website" />
        <meta
          property="og:url"
          content="https://main.d1tngp6p7622tv.amplifyapp.com/"
        />
        <meta
          property="og:image"
          content="http://localhost:3000/images/landing.png"
        />
        <meta
          property="og:description"
          content="Users can modify the designs what they in website this feature is available in our e-commerce website."
        />
        <meta name="language" content="English"></meta>
        
        {/* twitter card */}
        <meta name="twitter:card" content="E-commerce"></meta>
        <meta name="twitter:title" content="E-commerce website"></meta>
        <meta name="twitter:site" content="https://main.d1tngp6p7622tv.amplifyapp.com/"></meta>
        <meta name="twitter:image" content="http://localhost:3000/images/landing.png"></meta>

        {/* schema */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "http://www.schema.org",
            "@type": "WebSite",
            "name": "E-commerce",
            "alternateName": "Purchase",
            "url": "https://main.d1tngp6p7622tv.amplifyapp.com/",
          })
        }} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
